In [1]:
import itertools

In [2]:
study_variants = ["full", "ablation"]
schemas = ["dwc", "eml"]
strategies = ["data-focus", "author-focus"]
configurations = [
    dict(
        provider="openai-platform",
        core_platform="openai", 
        proxy_platform="openai", 
        core_llm="gpt-5.4-mini", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
    dict(
        provider="surf",
        core_platform="surf-pilot", 
        proxy_platform="openai", 
        core_llm="gpt-oss-120b", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-oss-120b"
    ),
    dict(
        provider="surf",
        core_platform="surf-pilot", 
        proxy_platform="openai", 
        core_llm="mistral-small-3.2", 
        embedding_model="text-embedding-3-small", 
        rag_llm="mistral-small-3.2"
    ),
    dict(
        provider="ivi",
        core_platform="surf-ivi", 
        proxy_platform="openai", 
        core_llm="o3-mini", 
        embedding_model="text-embedding-3-small", 
        rag_llm="o3-mini"
    ),
]

In [3]:
scenarios = list(itertools.product(study_variants, schemas, strategies, configurations))

In [4]:
scenarios

[('full',
  'dwc',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-oss-120b'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'mistral-small-3.2'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'o3-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-oss-120b'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'mistral-small-3.2'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'o3-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-oss-120b'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'mistral-small-3.2'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'o3-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-oss-120b'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'mistral-small-3.2'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'o3-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-oss-120b'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'mistral-small-3.2'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'o3-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-oss-120b'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'mistral-small-3.2'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'o3-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-oss-120b'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'mistral-small-3.2'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'o3-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-oss-120b'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'mistral-small-3.2'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'o3-mini'})]

In [5]:
len(scenarios)

32

In [6]:
added_configurations = [
    dict(
        provider="ivi",
        core_platform="surf-ivi", 
        proxy_platform="openai", 
        core_llm="gpt-5-mini", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5-mini"
    ),
]

In [7]:
added_scenarios = list(itertools.product(study_variants, schemas, strategies, added_configurations))

In [8]:
len(added_scenarios)

8

In [9]:
scenarios = scenarios + added_scenarios

In [10]:
len(scenarios)

40

In [11]:
import pandas as pd

In [12]:
scenario_records = [
    {
        "variant": s[0],
        "schema": s[1],
        "strategy": s[2],
        "provider": s[3]["provider"],
        "config": s[3],
    } for s in scenarios
]

In [13]:
scenarios_df = pd.DataFrame.from_records(scenario_records)

In [14]:
scenarios_df.describe(include="all")

,variant,schema,strategy,provider,config
count,40,40,40,40,40
unique,2,2,2,3,5
top,full,dwc,data-focus,surf,"{'provider': 'openai-platform', 'core_platform..."
freq,20,20,20,16,8

In [15]:
scenarios_df

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
1,full,dwc,data-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
2,full,dwc,data-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
3,full,dwc,data-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
4,full,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
5,full,dwc,author-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
6,full,dwc,author-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
7,full,dwc,author-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
8,full,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
9,full,eml,data-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
10,full,eml,data-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
11,full,eml,data-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
12,full,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
13,full,eml,author-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
14,full,eml,author-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
15,full,eml,author-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
16,ablation,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
17,ablation,dwc,data-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
18,ablation,dwc,data-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
19,ablation,dwc,data-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
20,ablation,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
21,ablation,dwc,author-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
22,ablation,dwc,author-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
23,ablation,dwc,author-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
24,ablation,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
25,ablation,eml,data-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
26,ablation,eml,data-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
27,ablation,eml,data-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
28,ablation,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
29,ablation,eml,author-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
30,ablation,eml,author-focus,surf,"{'provider': 'surf', 'core_platform': 'surf-pi..."
31,ablation,eml,author-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
32,full,dwc,data-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
33,full,dwc,author-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
34,full,eml,data-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
35,full,eml,author-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
36,ablation,dwc,data-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
37,ablation,dwc,author-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
38,ablation,eml,data-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."
39,ablation,eml,author-focus,ivi,"{'provider': 'ivi', 'core_platform': 'surf-ivi..."

In [16]:
scenarios_base_platform = scenarios_df[scenarios_df["config"].apply(lambda c: c["core_platform"] == "openai")]
scenarios_base_platform

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
4,full,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
8,full,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
12,full,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
16,ablation,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
20,ablation,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
24,ablation,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
28,ablation,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."

In [17]:
scenarios_base_platform_full = scenarios_base_platform[scenarios_base_platform["variant"]=="full"]
scenarios_base_platform_full

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
4,full,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
8,full,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
12,full,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."

In [18]:
import json

In [19]:
scenarios_df["config"] = scenarios_df["config"].apply(json.dumps)

In [20]:
scenarios_df.to_csv("experiment_scenarios.csv")

In [21]:
scenarios_df

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
1,full,dwc,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
2,full,dwc,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
3,full,dwc,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
4,full,dwc,author-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
5,full,dwc,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
6,full,dwc,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
7,full,dwc,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
8,full,eml,data-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
9,full,eml,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
10,full,eml,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
11,full,eml,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
12,full,eml,author-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
13,full,eml,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
14,full,eml,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
15,full,eml,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
16,ablation,dwc,data-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
17,ablation,dwc,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
18,ablation,dwc,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
19,ablation,dwc,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
20,ablation,dwc,author-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
21,ablation,dwc,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
22,ablation,dwc,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
23,ablation,dwc,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
24,ablation,eml,data-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
25,ablation,eml,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
26,ablation,eml,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
27,ablation,eml,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
28,ablation,eml,author-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
29,ablation,eml,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
30,ablation,eml,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
31,ablation,eml,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
32,full,dwc,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
33,full,dwc,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
34,full,eml,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
35,full,eml,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
36,ablation,dwc,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
37,ablation,dwc,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
38,ablation,eml,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
39,ablation,eml,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."

In [22]:
!diff "../_evaluation/runtime/experiment_scenarios.csv" "./experiment_scenarios.csv"