In [1]:
import itertools

In [2]:
study_variants = ["full", "ablation"]
schemas = ["dwc", "eml"]
strategies = ["data-focus", "author-focus"]
configurations = [
    dict(
        provider="openai-platform",
        core_platform="openai", 
        proxy_platform="openai", 
        core_llm="gpt-5.4-mini", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
    dict(
        provider="surf",
        core_platform="surf-pilot", 
        proxy_platform="openai", 
        core_llm="gpt-oss-120b", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
    dict(
        provider="surf",
        core_platform="surf-pilot", 
        proxy_platform="openai", 
        core_llm="mistral-small-3.2", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
    dict(
        provider="ivi",
        core_platform="surf-ivi", 
        proxy_platform="openai", 
        core_llm="o3-mini", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
]

In [3]:
scenarios = list(itertools.product(study_variants, schemas, strategies, configurations))

In [4]:
scenarios

[('full',
  'dwc',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'})]

In [5]:
len(scenarios)

32

In [6]:
import pandas as pd

In [7]:
scenario_records = [
    {
        "variant": s[0],
        "schema": s[1],
        "strategy": s[2],
        "provider": s[3]["provider"],
        "config": s[3],
    } for s in scenarios
]

In [8]:
scenarios_df = pd.DataFrame.from_records(scenario_records)

In [9]:
scenarios_df.describe(include="all")

,variant,schema,strategy,provider,config
count,32,32,32,32,32
unique,2,2,2,3,4
top,full,dwc,data-focus,surf,"{'provider': 'openai-platform', 'core_platform..."
freq,16,16,16,16,8

In [10]:
scenarios_base_platform = scenarios_df[scenarios_df["config"].apply(lambda c: c["core_platform"] == "openai")]
scenarios_base_platform

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
4,full,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
8,full,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
12,full,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
16,ablation,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
20,ablation,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
24,ablation,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
28,ablation,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."

In [11]:
scenarios_base_platform_full = scenarios_base_platform[scenarios_base_platform["variant"]=="full"]
scenarios_base_platform_full

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
4,full,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
8,full,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
12,full,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."

In [12]:
import json

In [13]:
scenarios_df["config"] = scenarios_df["config"].apply(json.dumps)

In [14]:
scenarios_df.to_csv("experiment_scenarios.csv")

In [18]:
s_x_c = pd.read_csv("experiment_cross_scenarios_cases.log.csv")

In [27]:
s_x_c["case_id"].apply(str).describe()

count     13
unique     6
top        0
freq       3
Name: case_id, dtype: object

In [28]:
s_x_c["case_tag"].apply(str).describe()

count                                                    13
unique                                                   13
top       c_0-x-s_0--full-dwc-data-focus-openai-platform...
freq                                                      1
Name: case_tag, dtype: object

In [31]:
for t in s_x_c["case_tag"].tolist():
    print(f"- {t}")

- c_0-x-s_0--full-dwc-data-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_2-x-s_2--full-dwc-data-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_3-x-s_3--full-dwc-data-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_4-x-s_4--full-dwc-data-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_0-x-s_5--full-dwc-author-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_2-x-s_7--full-dwc-author-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_3-x-s_8--full-dwc-author-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_4-x-s_9--full-dwc-author-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_5-x-s_5--full-dwc-data-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_6-x-s_6--full-dwc-data-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_0-x-s_7--full-dwc-author-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_2-x-s_9--full-dwc-author-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}
- c_3-x-s_10--full-dwc-author-focus-openai-platform-{'provider': 'openai-platform', 'core_platform': 'openai', 'proxy_platform': 'openai', 'core_llm': 'gpt-5.4-mini', 'embedding_model': 'text-embedding-3-small', 'rag_llm': 'gpt-5.4-mini'}

In [32]:
scenarios_df

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
1,full,dwc,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
2,full,dwc,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
3,full,dwc,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
4,full,dwc,author-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
5,full,dwc,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
6,full,dwc,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
7,full,dwc,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
8,full,eml,data-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
9,full,eml,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
10,full,eml,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
11,full,eml,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
12,full,eml,author-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
13,full,eml,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
14,full,eml,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
15,full,eml,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
16,ablation,dwc,data-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
17,ablation,dwc,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
18,ablation,dwc,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
19,ablation,dwc,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
20,ablation,dwc,author-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
21,ablation,dwc,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
22,ablation,dwc,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
23,ablation,dwc,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
24,ablation,eml,data-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
25,ablation,eml,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
26,ablation,eml,data-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
27,ablation,eml,data-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."
28,ablation,eml,author-focus,openai-platform,"{""provider"": ""openai-platform"", ""core_platform..."
29,ablation,eml,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
30,ablation,eml,author-focus,surf,"{""provider"": ""surf"", ""core_platform"": ""surf-pi..."
31,ablation,eml,author-focus,ivi,"{""provider"": ""ivi"", ""core_platform"": ""surf-ivi..."